version: 2

sources:
  - name: staging
    database: dataengineeringzoomcamp-412520
    schema: week_4

    tables:
      - name: green_tripdata
      - name: yellow_tripdata
      - name: fhv_tripdata
